Testo.with_capture fixes for Windows (#179)
After a long battle against "permission denied" errors on Windows when deleting temporary files, I gave up and added an exception handler.

Here's one of these errors:

```
Error: Internal error in test framework: exception raised by 'finally': Sys_error("C:\\Users\\circleci\\AppData\\Local\\Temp\\build_2e4c01_dune\\testo-2ed4ea.out: Permission denied")
```

These errors would occur during the cleanup phase of temporary files if we were not catching and ignoring them. They are presumably due to remaining file handles under unclear circumstances involving redirections with `Unix.dup` and `Unix.dup2`. It is also unclear whether writing to a pipe instead of a temporary file would work better (I tried but was still getting the error). Pipes may at least prevent temp folder pollution by the virtue of being anonymous (presumably).

Besides ignoring errors on temp file deletions, this updated implementation also eliminates the creation of temporary files when redirecting stdout or stderr to non-temporary files, thus bypassing the aforementioned issue.

Closes #178

PR checklist:

- [x] Purpose of the code is evident to future readers
- [x] Tests are included or a PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was added to `CHANGES.md` for any user-facing change

Check out [`CONTRIBUTING.md`](https://github.com/semgrep/testo/blob/main/CONTRIBUTING.md) for more details.